#server:
#  port: 30000
#spring:
#  application:
#    name: gulimall-thrid-party
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848


#alibaba:
#  cloud:
#    access-key: xx
#    secret-key: xx
#    oss:
#      endpoint: xx
#      bucket: xx