#server:
#  port: 88
#spring:
#  application:
#    name: gulimall-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: coupon-route
#          uri: lb://gulimall-coupon
#          predicates:
#            - Path=/api/coupon/**
#          filters:
#            - RewritePath=/api/coupon/?(?<segment>.*), /coupon/$\{segment}
#
#        - id: product-route
#          uri: lb://gulimall-product
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - RewritePath=/api/product/?(?<segment>.*), /product/$\{segment}
#
#        - id: thrid-party-route
#          uri: lb://gulimall-thrid-party
#          predicates:
#            - Path=/api/thridParty/**
#          filters:
#            - RewritePath=/api/thridParty/?(?<segment>.*), /thridParty/$\{segment}
#
#        - id: admin-route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#
